### ISSUE TITLE
Replace bignum.h

### ISSUE THREAD

**Issue by slaperche-scality** [vrancurel/quadiron#16]
Currently, we handle bignum by using a wrapper around OpenSSL implementation.
I saw several drawbacks to that:
- we have to maintain the wrapper
- no support for 256-bit integer (it is commented out), and this is the default integer type in the blockchain.
- we have to handle different version of OpenSSL (see https://github.com/vrancurel/quadiron/pull/4)
- seems to rely a lot on memory allocation (not a big deal for now)

An alternative would be  [cpp_int](http://www.boost.org/doc/libs/1_66_0/libs/multiprecision/doc/html/boost_multiprecision/tut/ints/cpp_int.html) from the "multiprecision" package of Boost.
Advantage:
- almost no maintenance on our side
- native support for 128 and 256-bit integer
- support for 160-bit integer (address in the blockchain) is as easy as a typedef
- efficient code (it's Boost + it seems like default types are implemented with no new/malloc)

**Comment by vrancurel** [comment]
Lets use gmpxx

**Comment by slaperche-scality** [comment]
Another alternative would be [gmpxx](https://gmplib.org/manual/C_002b_002b-Class-Interface.html#C_002b_002b-Class-Interface), which is already used by NTL.

**Comment by slaperche-scality** [comment]
Replaced by an homemade implementation (see #46)
