### ISSUE TITLE
Add cpplint to the project

### ISSUE THREAD

**Issue by vrancurel** [vrancurel/quadiron#7]
See https://github.com/vrancurel/ntl

**Comment by slaperche-scality** [comment]
[clang-tidy](https://clang.llvm.org/extra/clang-tidy/) could also be a good option, it seems very complete and easy to configure.

**Comment by vrancurel** [comment]
ok lets do clang-tidy

**Comment by slaperche-scality** [comment]
I'm on it (don't know how to assign it to myself on github)
